apiVersion: v1
items:
- apiVersion: batch/v1
  kind: Job
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"batch/v1","kind":"Job","metadata":{"annotations":{},"name":"naame","namespace":"tool-test"},"spec":{"backoffLimit":3,"template":{"spec":{"containers":[{"command":["mycmd"],"env":[{"name":"HOME","value":"/data/project/test"}],"image":"docker-registry.tools.wmflabs.org/toolforge-buster-sssd:latest","name":"naame","volumeMounts":[{"mountPath":"/data/project","name":"home"}],"workingDir":"/data/project/test"}],"restartPolicy":"Never","volumes":[{"hostPath":{"path":"/data/project","type":"Directory"},"name":"home"}]}}}}
    creationTimestamp: "2021-02-04T12:14:05Z"
    labels:
      controller-uid: 008313de-1bc3-4ed0-8ffa-eabac0f719b5
      job-name: naame
    name: naame
    namespace: tool-test
    resourceVersion: "95222124"
    selfLink: /apis/batch/v1/namespaces/tool-test/jobs/naame
    uid: 008313de-1bc3-4ed0-8ffa-eabac0f719b5
  spec:
    backoffLimit: 3
    completions: 1
    parallelism: 1
    selector:
      matchLabels:
        controller-uid: 008313de-1bc3-4ed0-8ffa-eabac0f719b5
    template:
      metadata:
        creationTimestamp: null
        labels:
          controller-uid: 008313de-1bc3-4ed0-8ffa-eabac0f719b5
          job-name: naame
      spec:
        containers:
        - command:
          - mycmd
          env:
          - name: HOME
            value: /data/project/test
          image: docker-registry.tools.wmflabs.org/toolforge-buster-sssd:latest
          imagePullPolicy: Always
          name: naame
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /data/project
            name: home
          workingDir: /data/project/test
        dnsPolicy: ClusterFirst
        restartPolicy: Never
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - hostPath:
            path: /data/project
            type: Directory
          name: home
  status:
    conditions:
    - lastProbeTime: "2021-02-04T12:15:48Z"
      lastTransitionTime: "2021-02-04T12:15:48Z"
      message: Job has reached the specified backoff limit
      reason: BackoffLimitExceeded
      status: "True"
      type: Failed
    failed: 3
    startTime: "2021-02-04T12:14:05Z"
- apiVersion: batch/v1
  kind: Job
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"batch/v1","kind":"Job","metadata":{"annotations":{},"name":"name2","namespace":"tool-test"},"spec":{"backoffLimit":3,"template":{"spec":{"containers":[{"command":["mycmd"],"env":[{"name":"HOME","value":"/data/project/test"}],"image":"docker-registry.tools.wmflabs.org/toolforge-buster-sssd:latest","name":"name2","volumeMounts":[{"mountPath":"/data/project","name":"home"}],"workingDir":"/data/project/test"}],"restartPolicy":"Never","volumes":[{"hostPath":{"path":"/data/project","type":"Directory"},"name":"home"}]}}}}
    creationTimestamp: "2021-02-04T12:14:31Z"
    labels:
      controller-uid: 7b46b4cf-2882-4842-9bb8-384022100731
      job-name: name2
    name: name2
    namespace: tool-test
    resourceVersion: "95222195"
    selfLink: /apis/batch/v1/namespaces/tool-test/jobs/name2
    uid: 7b46b4cf-2882-4842-9bb8-384022100731
  spec:
    backoffLimit: 3
    completions: 1
    parallelism: 1
    selector:
      matchLabels:
        controller-uid: 7b46b4cf-2882-4842-9bb8-384022100731
    template:
      metadata:
        creationTimestamp: null
        labels:
          controller-uid: 7b46b4cf-2882-4842-9bb8-384022100731
          job-name: name2
      spec:
        containers:
        - command:
          - mycmd
          env:
          - name: HOME
            value: /data/project/test
          image: docker-registry.tools.wmflabs.org/toolforge-buster-sssd:latest
          imagePullPolicy: Always
          name: name2
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /data/project
            name: home
          workingDir: /data/project/test
        dnsPolicy: ClusterFirst
        restartPolicy: Never
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - hostPath:
            path: /data/project
            type: Directory
          name: home
  status:
    conditions:
    - lastProbeTime: "2021-02-04T12:16:10Z"
      lastTransitionTime: "2021-02-04T12:16:10Z"
      message: Job has reached the specified backoff limit
      reason: BackoffLimitExceeded
      status: "True"
      type: Failed
    failed: 4
    startTime: "2021-02-04T12:14:57Z"
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
