# base values file
replicas: 2

webservice:
  image:
    repository: docker-registry.tools.wmflabs.org/toolforge-jobs-framework-api
    tag: 3569803
    pullpolicy: Always
nginx:
  image:
    repository: docker-registry.tools.wmflabs.org/nginx
    tag: latest
    pullpolicy: Always

certificates:
  apiGatewayCa:
    name: api-gateway-backend-ca
    kind: ClusterIssuer
    group: cert-manager.io
