---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jobs-api
  namespace: jobs-api
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jobs-api-psp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: privileged-psp
subjects:
- kind: ServiceAccount
  name: jobs-api
  namespace: jobs-api
---
apiVersion: v1
kind: Service
metadata:
  name: jobs-api
  namespace: jobs-api
spec:
  type: NodePort
  ports:
    - name: https
      nodePort: 30001
      port: 30001
      targetPort: 30001
      protocol: TCP
  selector:
    name: jobs-api
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: jobs-api
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;

    events {
        worker_connections 1024;
    }

    http {
        server {
            listen 30001 ssl;

            ssl_certificate        /etc/nginx/ssl/tls.crt;
            ssl_certificate_key    /etc/nginx/ssl/tls.key;
            ssl_client_certificate /var/run/secrets/kubernetes.io/serviceaccount/ca.crt;
            ssl_verify_client      on;
            ssl_protocols          TLSv1.1 TLSv1.2;
            ssl_ciphers            HIGH:!aNULL:!MD5;

            location / {
                include uwsgi_params;
                uwsgi_pass localhost:8000;
                uwsgi_param HTTP_SSL_CLIENT_SUBJECT_DN $ssl_client_s_dn;
            }
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jobs-api-containers
  namespace: jobs-api
data:
  containers.yaml: |
    ---
    - shortname: tf-bullseye-std
      image: docker-registry.tools.wmflabs.org/toolforge-bullseye-standalone:latest
    - shortname: tf-buster-std
      image: docker-registry.tools.wmflabs.org/toolforge-buster-standalone:latest
    - shortname: tf-golang
      image: docker-registry.tools.wmflabs.org/toolforge-golang-sssd-base:latest
    - shortname: tf-golang111
      image: docker-registry.tools.wmflabs.org/toolforge-golang111-sssd-base:latest
    - shortname: tf-jdk17
      image: docker-registry.tools.wmflabs.org/toolforge-jdk11-sssd-base:latest
    - shortname: tf-jdk11
      image: docker-registry.tools.wmflabs.org/toolforge-jdk11-sssd-base:latest
    - shortname: tf-jdk8-DEPRECATED
      image: docker-registry.tools.wmflabs.org/toolforge-jdk8-sssd-base:latest
    - shortname: tf-node12
      image: docker-registry.tools.wmflabs.org/toolforge-node12-sssd-base:latest
    - shortname: tf-node10
      image: docker-registry.tools.wmflabs.org/toolforge-node10-sssd-base:latest
    - shortname: tf-node6-DEPRECATED
      image: docker-registry.tools.wmflabs.org/toolforge-node6-sssd-base:latest
    - shortname: tf-php5-DEPRECATED
      image: docker-registry.tools.wmflabs.org/toolforge-php5-sssd-base:latest
    - shortname: tf-php72-DEPRECATED
      image: docker-registry.tools.wmflabs.org/toolforge-php72-sssd-base:latest
    - shortname: tf-php73
      image: docker-registry.tools.wmflabs.org/toolforge-php73-sssd-base:latest
    - shortname: tf-php74
      image: docker-registry.tools.wmflabs.org/toolforge-php74-sssd-base:latest
    - shortname: tf-python2-DEPRECATED
      image: docker-registry.tools.wmflabs.org/toolforge-python2-sssd-base:latest
    - shortname: tf-python34-DEPRECATED
      image: docker-registry.tools.wmflabs.org/toolforge-python34-sssd-base:latest
    - shortname: tf-python35-DEPRECATED
      image: docker-registry.tools.wmflabs.org/toolforge-python35-sssd-base:latest
    - shortname: tf-python37
      image: docker-registry.tools.wmflabs.org/toolforge-python37-sssd-base:latest
    - shortname: tf-python39
      image: docker-registry.tools.wmflabs.org/toolforge-python39-sssd-base:latest
    - shortname: tf-ruby21-DEPRECATED
      image: docker-registry.tools.wmflabs.org/toolforge-ruby21-sssd-base:latest
    - shortname: tf-ruby25
      image: docker-registry.tools.wmflabs.org/toolforge-ruby25-sssd-base:latest
    - shortname: tf-ruby27
      image: docker-registry.tools.wmflabs.org/toolforge-ruby27-sssd-base:latest
    - shortname: tf-tcl86
      image: docker-registry.tools.wmflabs.org/toolforge-tcl86-sssd-base:latest
    - shortname: wm-bullseye
      image: docker-registry.tools.wmflabs.org/wikimedia-bullseye:latest
    - shortname: wm-buster
      image: docker-registry.tools.wmflabs.org/wikimedia-buster:latest
    - shortname: wm-stretch-DEPRECATED
      image: docker-registry.tools.wmflabs.org/wikimedia-stretch:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobs-api
  namespace: jobs-api
  labels:
    name: jobs-api
spec:
  replicas: 2
  selector:
    matchLabels:
      name: jobs-api
  template:
    metadata:
      labels:
        name: jobs-api
    spec:
      serviceAccountName: jobs-api
      volumes:
      - name: home
        hostPath:
          path: /data/project
          type: Directory
      - name: wmcs-project
        hostPath:
          path: /etc/wmcs-project
          type: File
      - name: sssd-pipes
        hostPath:
          path: /var/lib/sss/pipes
          type: Directory
      - name: nginx-config
        configMap:
          name: nginx-config
          items:
            - key: nginx.conf
              path: nginx.conf
      - name: jobs-api-server-cert
        secret:
          secretName: jobs-api-server-cert
      - name: jobs-api-containers
        configMap:
          name: jobs-api-containers
          items:
            - key: containers.yaml
              path: containers.yaml
      containers:
        - name: webservice
          image: docker-registry.tools.wmflabs.org/toolforge-jobs-framework-api:latest
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /data/project
            name: home
          - mountPath: /etc/wmcs-project
            name: wmcs-project
            readOnly: true
          - mountPath: /var/lib/sss/pipes
            name: sssd-pipes
          - name: jobs-api-containers
            mountPath: /etc/containers.yaml
            subPath: containers.yaml
            readOnly: true
        - name: nginx
          image: docker-registry.tools.wmflabs.org/nginx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 30001
              name: https
              protocol: TCP
          volumeMounts:
          - mountPath: /etc/nginx/ssl
            name: jobs-api-server-cert
            readOnly: true
          - name: nginx-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
            readOnly: true
---
