---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jobs-api-psp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: privileged-psp
subjects:
- kind: ServiceAccount
  name: jobs-api
  namespace: jobs-api
---
# https://github.com/kubernetes/ingress-nginx
apiVersion: v1
kind: Namespace
metadata:
  name: jobs-api
  labels:
    # we need this label to bypass the ingress-admission controller
    name: jobs-api
    app.kubernetes.io/name: ingress-nginx-jobs
    app.kubernetes.io/part-of: ingress-nginx-jobs
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration
  namespace: jobs-api
  labels:
    app.kubernetes.io/name: ingress-nginx-jobs
    app.kubernetes.io/part-of: ingress-nginx-jobs
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: tcp-services
  namespace: jobs-api
  labels:
    app.kubernetes.io/name: ingress-nginx-jobs
    app.kubernetes.io/part-of: ingress-nginx-jobs
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: udp-services
  namespace: jobs-api
  labels:
    app.kubernetes.io/name: ingress-nginx-jobs
    app.kubernetes.io/part-of: ingress-nginx-jobs
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jobs-api
  namespace: jobs-api
  labels:
    app.kubernetes.io/name: ingress-nginx-jobs
    app.kubernetes.io/part-of: ingress-nginx-jobs
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: jobs-api
  labels:
    app.kubernetes.io/name: ingress-nginx-jobs
    app.kubernetes.io/part-of: ingress-nginx-jobs
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - endpoints
      - nodes
      - pods
      - secrets
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - "extensions"
      - "networking.k8s.io"
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "extensions"
      - "networking.k8s.io"
    resources:
      - ingresses/status
    verbs:
      - update

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: jobs-api
  namespace: jobs-api
  labels:
    app.kubernetes.io/name: ingress-nginx-jobs
    app.kubernetes.io/part-of: ingress-nginx-jobs
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - pods
      - secrets
      - namespaces
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      # Defaults to "<election-id>-<ingress-class>"
      # Here: "<ingress-controller-leader>-<nginx>"
      # This has to be adapted if you change either parameter
      # when launching the nginx-ingress-controller.
      - "ingress-controller-leader-jobs"
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: jobs-api
  namespace: jobs-api
  labels:
    app.kubernetes.io/name: ingress-nginx-jobs
    app.kubernetes.io/part-of: ingress-nginx-jobs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jobs-api
subjects:
  - kind: ServiceAccount
    name: jobs-api
    namespace: jobs-api
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: jobs-api
  labels:
    app.kubernetes.io/name: ingress-nginx-jobs
    app.kubernetes.io/part-of: ingress-nginx-jobs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jobs-api
subjects:
  - kind: ServiceAccount
    name: jobs-api
    namespace: jobs-api

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-nginx-jobs
  namespace: jobs-api
  labels:
    app.kubernetes.io/name: ingress-nginx-jobs
    app.kubernetes.io/part-of: ingress-nginx-jobs
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx-jobs
      app.kubernetes.io/part-of: ingress-nginx-jobs
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ingress-nginx-jobs
        app.kubernetes.io/part-of: ingress-nginx-jobs
      annotations:
        prometheus.io/port: "10254"
        prometheus.io/scrape: "true"
    spec:
      serviceAccountName: jobs-api
      # affinity and taints, only schedule pods in ingress nodes
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - ingress
      tolerations:
        - key: "ingress"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      containers:
        - name: nginx-ingress-controller
          image: docker-registry.tools.wmflabs.org/nginx-ingress-controller:0.25.1
          args:
            - /nginx-ingress-controller
            - --http-port=30001
            - --configmap=$(POD_NAMESPACE)/nginx-configuration
            - --tcp-services-configmap=$(POD_NAMESPACE)/tcp-services
            - --udp-services-configmap=$(POD_NAMESPACE)/udp-services
            - --publish-service=$(POD_NAMESPACE)/ingress-nginx-jobs
            - --annotations-prefix=nginx.ingress.kubernetes.io
            - --ingress-class=jobs
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
            # www-data -> 33
            runAsUser: 33
          resources:
            requests:
              cpu: "0.5"
              memory: "1Gi"
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: http
              containerPort: 30001
            - name: metrics
              containerPort: 10254
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 10254
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 10254
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10

---
# from https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/baremetal/service-nodeport.yaml
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-jobs-api
  namespace: jobs-api
  labels:
    app.kubernetes.io/name: ingress-nginx-jobs
    app.kubernetes.io/part-of: ingress-nginx-jobs
spec:
  type: NodePort
  ports:
    - name: http
      nodePort: 30001
      port: 30001
      targetPort: 30001
      protocol: TCP
  selector:
    app.kubernetes.io/name: ingress-nginx-jobs
    app.kubernetes.io/part-of: ingress-nginx-jobs
---
# the jobs-api itself
apiVersion: v1
kind: Service
metadata:
  name: jobs-api
  namespace: jobs-api
  labels:
    name: jobs-api
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: jobs-api
  type: ClusterIP
---
# kubectl -n jobs-api create secret generic k8s-ca-secret --from-file=ca.crt=/etc/kubernetes/pki/ca.crt
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: k8s-ca-secret
  namespace: jobs-api
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNU1UQXlNekE1TlRRMU5Gb1hEVEk1TVRBeU1EQTVOVFExTkZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBT2xjCmJwK29lUlYrM1N2K3pYN1FsTVZSeVI2NnBPK1lPUTYwUVd0M0xxVUtRODRhQXpoVHJWek5NMmVxQ2IxWlZGUFMKTlRzczBwMTFUMUsrQzdVSndBRkFmOHV1RTlGNjFkVHpSMnNuT2ZmTUdDalZVT0txZEJucDNaTUlDMDhGOVlsagpndWc2bXQ5L1RFRGNML2RETDZpOEtQS1VmSC96cXdvUkpBUjVOUDVMelVPYVBrMzJxaUJqYjQ2UWVyZ3o3Z2VHCjQxOHRjTnc5aGsrZFBWMTdUdFRkUEg4NGQ5TlFaMnpDWGp5SnhaNnNWZlE0SDcyWml1cUFVbmx2UVJFTEs1c2YKR2JSYUpWWTk0U1J5K3IwenF0L2ptbjloNW1SckcxMW9Lb2w1ZnRZWGtyTHo2MWJDclltVFVHQjd4Q3JyL1lLUApVMmlqdnhQRnF1Y1Q2Q2trVjkwQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFEaTlwOEgwS3pJdlo5VWl1MXd0S3E5NXdiM3cKK1BUTk9ldDVRK0ZzdmRrY1RacHpmbU0xNGZsWDhPQS8zd2RLK0tPcGhSWU15c0lyTE5yQ3k0REhrUnhHaElJbAo3RDZPeDgvOUFUb0VhVXJ1a1FKMWJORWR0Q2ZicHBWYUlFYW9zYVJuZW9FdDgwREZWRUJqN1lWbDlISjlvODhRCjZXQXFQQnRPdVJ5ZDRKVDgrdjlQZU40RGlKejNQaTczRHdwYW9yb2U0aWdaUEtuK0FRS1Q3VURtWjBaNXR1RXoKOW9ieklRMzNObjdOZENpZEdTVUdGWFJOOUVPaUJNYlR6ai9VVFFnbDd3RWpXTGZXY0k0Y3MxNzhBV1pLYlIzbwp3U2R0OERSVlhlbTg0NnpYc0ZVb2tTQ2RWOGlmRmFzeTM0Zjd1enFoT01oN1UrRVdKdkFvakVXRUJaWT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
---
# from https://kubernetes.github.io/ingress-nginx/examples/auth/client-certs/
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: jobs-api
  namespace: jobs-api
  annotations:
    # Enable client certificate authentication
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    # Create the secret containing the trusted ca certificates
    # # this was created using: kubectl create secret generic k8s-ca-secret --from-file=ca.crt=/etc/kubernetes/pki/ca.crt
    nginx.ingress.kubernetes.io/auth-tls-secret: "jobs-api/k8s-ca-secret"
    # Specify the verification depth in the client certificates chain
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
    # Specify if certificates are passed to upstream server
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
    # special ingress
    kubernetes.io/ingress.class: "jobs"
spec:
  rules:
  - host: jobs.svc.toolsbeta.eqiad1.wikimedia.cloud
    http:
      paths:
      - backend:
          serviceName: jobs-api
          servicePort: 8080
        path: /
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobs-api
  namespace: jobs-api
  labels:
    name: jobs-api
spec:
  replicas: 1
  selector:
    matchLabels:
      name: jobs-api
  template:
    metadata:
      labels:
        name: jobs-api
    spec:
      serviceAccountName: jobs-api
      volumes:
      - name: home
        hostPath:
          path: /data/project
          type: Directory
      - name: wmcs-project
        hostPath:
          path: /etc/wmcs-project
          type: File
      - name: sssd-pipes
        hostPath:
          path: /var/lib/sss/pipes
          type: Directory
      containers:
        - name: webservice
          image: docker-registry.tools.wmflabs.org/toolforge-jobs-framework-api:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          volumeMounts:
          - mountPath: /data/project
            name: home
          - mountPath: /etc/wmcs-project
            name: wmcs-project
            readOnly: true
          - mountPath: /var/lib/sss/pipes
            name: sssd-pipes
---
