---
apiVersion: v1
kind: ConfigMap
metadata:
  name: images
data:
  images.yaml: |
    ---
    - shortname: tf-bullseye-std
      image: docker-registry.tools.wmflabs.org/toolforge-bullseye-sssd:latest
    - shortname: tf-bullseye-std-DEPRECATED
      image: docker-registry.tools.wmflabs.org/toolforge-bullseye-standalone:latest
    - shortname: tf-buster-std-DEPRECATED
      image: docker-registry.tools.wmflabs.org/toolforge-buster-standalone:latest
    - shortname: tf-golang
      image: docker-registry.tools.wmflabs.org/toolforge-golang-sssd-base:latest
    - shortname: tf-golang111
      image: docker-registry.tools.wmflabs.org/toolforge-golang111-sssd-base:latest
    - shortname: tf-jdk17
      image: docker-registry.tools.wmflabs.org/toolforge-jdk17-sssd-base:latest
    - shortname: tf-jdk11-DEPRECATED
      image: docker-registry.tools.wmflabs.org/toolforge-jdk11-sssd-base:latest
    - shortname: tf-jdk8-DEPRECATED
      image: docker-registry.tools.wmflabs.org/toolforge-jdk8-sssd-base:latest
    - shortname: tf-mono68
      image: docker-registry.tools.wmflabs.org/toolforge-mono68-sssd-base:latest
    - shortname: tf-node16
      image: docker-registry.tools.wmflabs.org/toolforge-node16-sssd-base:latest
    - shortname: tf-node12
      image: docker-registry.tools.wmflabs.org/toolforge-node12-sssd-base:latest
    - shortname: tf-node10-DEPRECATED
      image: docker-registry.tools.wmflabs.org/toolforge-node10-sssd-base:latest
    - shortname: tf-node6-DEPRECATED
      image: docker-registry.tools.wmflabs.org/toolforge-node6-sssd-base:latest
    - shortname: tf-perl532
      image: docker-registry.tools.wmflabs.org/toolforge-perl532-sssd-base:latest
    - shortname: tf-php5-DEPRECATED
      image: docker-registry.tools.wmflabs.org/toolforge-php5-sssd-base:latest
    - shortname: tf-php72-DEPRECATED
      image: docker-registry.tools.wmflabs.org/toolforge-php72-sssd-base:latest
    - shortname: tf-php73-DEPRECATED
      image: docker-registry.tools.wmflabs.org/toolforge-php73-sssd-base:latest
    - shortname: tf-php74
      image: docker-registry.tools.wmflabs.org/toolforge-php74-sssd-base:latest
    - shortname: tf-python2-DEPRECATED
      image: docker-registry.tools.wmflabs.org/toolforge-python2-sssd-base:latest
    - shortname: tf-python34-DEPRECATED
      image: docker-registry.tools.wmflabs.org/toolforge-python34-sssd-base:latest
    - shortname: tf-python35-DEPRECATED
      image: docker-registry.tools.wmflabs.org/toolforge-python35-sssd-base:latest
    - shortname: tf-python37-DEPRECATED
      image: docker-registry.tools.wmflabs.org/toolforge-python37-sssd-base:latest
    - shortname: tf-python39
      image: docker-registry.tools.wmflabs.org/toolforge-python39-sssd-base:latest
    - shortname: tf-ruby21-DEPRECATED
      image: docker-registry.tools.wmflabs.org/toolforge-ruby21-sssd-base:latest
    - shortname: tf-ruby25-DEPRECATED
      image: docker-registry.tools.wmflabs.org/toolforge-ruby25-sssd-base:latest
    - shortname: tf-ruby27
      image: docker-registry.tools.wmflabs.org/toolforge-ruby27-sssd-base:latest
    - shortname: tf-tcl86
      image: docker-registry.tools.wmflabs.org/toolforge-tcl86-sssd-base:latest
